/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package herencia;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author Laptop
 */
//hola mundo
public final class principal extends javax.swing.JFrame {
    BotonContador botonmodas;
    BotonContador botonb;
    BotonContador botonc;
    BotonContador botond;
    
  
    /**
     * Creates new form principal
     */
    
    
 
    public principal() {
        initComponents();
        CreacionVentana();
    }
    
    
   
   
    public void CreacionVentana(){
        this.setTitle("Ejercicio Pulsaciones");
        this.setSize(250, 300);
        
        botona = new BotonContador();
        botona.setText("botonA");
        botona.setBounds(10, 10, 100, 30);
        this.getContentPane().add(botona);
        
        botonb = new BotonContador();
        botonb.setText("botonB");
        botonb.setBounds(130, 10, 100, 30);
        this.getContentPane().add(botonb);
        
        
        botonc = new BotonContador();
        botonc.setText("botonC");
        botonc.setBounds(30, 40, 80, 40);
        this.getContentPane().add(botonc);
        
        botond = new BotonContador();
        botond.setText("botonD");
        botond.setBounds(150, 40, 80, 40);
        this.getContentPane().add(botond);
        
        
            botona.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt){
                botonaActionPerformed(evt);
            }
            });
            botonb.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt){
                botonaActionPerformed(evt);
            }
            });
            
            botonc.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt){
                botonaActionPerformed(evt);
            }
            });
            
            botond.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt){
                botonaActionPerformed(evt);
            }
            });
            
            
            
}
    public void botonaActionPerformed(ActionEvent evt){
       botona.incrementa();
    }
    
    public void botonbActionPerformed(ActionEvent evt){
       botonb.incrementa();
    }
    
    public void botoncActionPerformed(ActionEvent evt) {
        botonc.incrementa();
    }
    
    public void botondActionPerformed(ActionEvent evt) {
        botond.incrementa();
    }
    
        
    
    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(86, 86, 86))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(183, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(94, 94, 94))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    JOptionPane.showMessageDialog(null,"las pulsaciones del boton A son: "+botona.getPulsaciones()+".");
    JOptionPane.showMessageDialog(null,"las pulsaciones del boton B son: "+botonb.getPulsaciones()+".");
    JOptionPane.showMessageDialog(null,"las pulsaciones del boton C son: "+botonc.getPulsaciones()+".");
    JOptionPane.showMessageDialog(null,"las pulsaciones del boton D son: "+botond.getPulsaciones()+".");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JOptionPane.showMessageDialog(null,"las pulsaciones del boton A son: "+botona.getPulsaciones()+".");
    JOptionPane.showMessageDialog(null,"las pulsaciones del boton B son: "+botonb.getPulsaciones()+".");
    JOptionPane.showMessageDialog(null,"las pulsaciones del boton C son: "+botonc.getPulsaciones()+".");
    JOptionPane.showMessageDialog(null,"las pulsaciones del boton D son: "+botond.getPulsaciones()+".");
  
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
